---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-operator-default-ns-project

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cr-operator-default-ns-project
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crb-operator-default-ns-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-operator-default-ns-project
subjects:
  - kind: ServiceAccount
    name: sa-operator-default-ns-project
    namespace: {{ .Release.Namespace }}
